export const productType = {
  GET_PRODUCT_CATEGORY_SUCCESS: "GET_PRODUCT_CATEGORY_SUCCESS",
  GET_PRODUCT_CATEGORY_FAILURE: "GET_PRODUCT_CATEGORY_FAILURE",
  GET_PRODUCT_CATEGORY_LOADING: "GET_PRODUCT_CATEGORY_LOADING",

  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  GET_PRODUCTS_LOADING: "GET_PRODUCTS_LOADING",

  SET_PRODUCT_BY_ID: "SET_PRODUCT_BY_ID",

  ITEM_COUNT: "ITEM_COUNT",
};
